let colors = [
  "Persian Violet",
  "Opti Yellow",
  "Green Strike",
  "Total Orange",
  "Photo Blue",
  "Red",
"Fluo Coral",
"Fluo Green",
"Fluo Yellow",
"Turquoise Navy",
"Fluo Pink Black",
"Black White",
"Orange Black",
"Fluo Green Black",
"Fluo Yellow Navy",
"Red Black",

  "Imperial Red",
  "Folly",
  "Strawberry",
  "Carmine",
  "Alizarin Crimson",
  "Neon Red",
  "Cardinals Red",
  "Bright Red",
  "Candy Apple Red",
  "Crimson",
  "Carmine Red",
  "Electric Crimson",
  "Ferrari",
  "Maroon",
  "Crayola Red",
  "Orange Red",
  "Scarlet",
  "Cincinnati Red",
  "Raspberry",
  "Fire Engine Red",
  "Harvard Crimson",
  "Ruddy",
  "Amaranth Red",
  "Cherry Red",
  "Auburn Red",
  "Spanish Red",
  "Rose Madder",
  "Cherry",
  "Carmine",
  "Rosso Corsa",
  "Rubine Red",
  "Boston University Red",
  "Ruby",
  "Red Tape",
  "Bright Red",
  "Smashing",
  "Poppy",
  "Cranberry",
  "Lipstick Red",
  "Rose Red",
  "Monza",
  "Venetian Red",
  "Vermillion",
  "Lava",
  "Red Pepper",
  "Knock Out",
  "Lust",
  "Firebrick",
  "Rufous",
  "Brick Red",
  "Scarlett",
  "Blood Red",
  "Wine",
  "Sangria",
  "Merlot",
  "Burgundy",
  "Maroon",
  "Bordeaux",
  "Blood",
  "Salsa",
  "Cedar Wood Finish",
  "Claret",
  "Burnt Crimson",
  "Castro",
  "Mahogany",
  "Blush",
  "Alluring",
  "Pastel pink",
  "Amaranth Pink",
  "Amour",
  "Bubblegum",
  "Azalea",
  "Baby Pink",
  "Baby Pink",
  "Ballerina",
  "Bambina",
  "Barbie Pink",
  "Beauty Bush",
  "Birthday Suit",
  "Blossom",
  "Blush Pink",
  "Boutique",
  "Brandy Rose",
  "Bridesmaid",
  "Bright Pink",
  "Brink Pink",
  "Coral",
  "Brownish Pink",
  "Bubble Gum",
  "Hit Pink",
  "Light Coral",
  "Cameo Pink",
  "Can",
  "Candy Pink",
  "Crepe",
  "Careys Pink",
  "Carissma",
  "Carnation Pink",
  "Cerise Pink",
  "Chantilly",
  "Charm",
  "Classic Rose",
  "Congo Pink",
  "Coral Pink",
  "Cornflower Lilac",
  "Barbie Pink",
  "Cosmos",
  "Mulberry",
  "Cupid",
  "Dark Pink",
  "Lace",
  "Deep Blush",
  "Oyster",
  "Dirty Pink",
  "Dull Pink",
  "Dusty Pink",
  "English Lavender",
  "Faded Pink",
  "Flamingo Pink",
  "Floyd",
  "French Fuchsia",
  "Light French Pink",
  "Gray Pink",
  "French Rose",
  "Hopbush",
  "Kidman",
  "Puce",
  "Hot Pink ",
  "Kobi",
  "Raspberry Rose",
  "Lavender Rose",
  "Paradise Pink",
  "Light Hot Pink",
  "Light Thulian Pink",
  "Lullaby",
  "Magenta Pink",
  "Tulip Pink",
  "Mamma Mia",
  "Mandys Pink",
  "French Pink",
  "Marshmallow",
  "Maverick",
  "Mesmerise",
  "Mountbatten Pink",
  "Muted Pink",
  "My Pink",
  "Nadeshiko Pink",
  "New York Pink",
  "Old Pink",
  "Old Rose",
  "Orchid Pink",
  "Oriental Pink",
  "Oyster Pink",
  "Pale Pink",
  "Pink Lace",
  "Pink Lavender",
  "Pink Light",
  "Pink Salmon",
  "Pink Sherbet",
  "Pinkish",
  "Pinky",
  "Powder Pink",
  "Queen Pink",
  "Rosa",
  "Rose",
  "Rose Bonbon",
  "Rosy Pink",
  "Ruddy Pink",
  "Sakura",
  "Schauss Pink",
  "Shimmering Blush",
  "Steel Pink",
  "Strong Pink",
  "Super Pink",
  "Sweet Pink",
  "Mauvelous",
  "Brink",
  "Nude Pink",
  "Tango Pink",
  "Thulian Pink",
  "Violet Pink",
  "Warm Pink",
  "Wax Flower",
  "Wewak",
  "Sweet Pink",
  "Wild Watermelon",
  "Zinnwaldite",
  "Adrenalin",
  "Orange",
  "Halloween Orange",
  "Dark Orange",
  "Tangelo",
  "Royal Orange",
  "Pastel Orange",
  "Coral Orange",
  "Princeton Orange",
  "Alamo",
  "Crayola Orange",
  "Tangerine",
  "Vivid Orange",
  "Cheese Orange",
  "Alloy Orange",
  "Desert Orange",
  "Amber",
  "Flame",
  "Irish Orange",
  "Apricot",
  "Metallic Orange",
  "Ayers Rock",
  "Goldfish Orange",
  "Mango Tango",
  "Willpower Orange",
  "Bamboo",
  "Lava Orange",
  "Beethoven",
  "Big Foot Feet",
  "Dusty Orange",
  "Dutch Orange",
  "Biscuit Brown",
  "Blaze Orange",
  "Peach Orange",
  "Blood Orange",
  "Bourbon",
  "Safety Orange",
  "Brick Orange",
  "Bright Orange",
  "Chocolate Orange",
  "Brilliant Orange",
  "Brilliant Scarlet",
  "Salmon Orange",
  "Brilliant Tangelo",
  "Syracuse Orange",
  "Brilliant Vermilion",
  "Burning Orange",
  "Burnt Orange",
  "Burnt Siena",
  "Cadmium Orange",
  "Tiger Orange",
  "California",
  "Greek Orange",
  "West Side Orange",
  "Carpe Diem",
  "Yam Orange",
  "Carrot",
  "Cinnabar",
  "Marigold Orange",
  "Clementine",
  "Coral",
  "Deep Carrot Orange",
  "Dusty Orange",
  "Neon Orange",
  "Koi Orange",
  "Flush Orange",
  "Frenzee",
  "Rubber Duck",
  "Salamander Orange",
  "India Saffron",
  "Fulvous",
  "Giants Orange",
  "Gold Drop",
  "Spanish Orange",
  "Guggenheim",
  "Persimmon",
  "Heat Wave",
  "Terracotta",
  "Juicy",
  "Mandarin",
  "Orange Peel",
  "Peach Orange",
  "Vivid Tangelo",
  "Pizazz",
  "Buff Orange",
  "Pomegranate",
  "Pumpkin",
  "Mango",
  "Bronze Orange",
  "Aureoline",
  "Bumblebee",
  "School Bus",
  "Beige",
  "Sunshine Yellow",
  "Macaroon",
  "Honey",
  "Canary Yellow",
  "Spanish Yellow",
  "Golden Tainoi",
  "Banana",
  "Light Khaki",
  "Tuscany",
  "Yellow – Pantone",
  "Banana",
  "Vivid Yellow",
  "Light Brilliant Amber",
  "Amber",
  "Bright Yellow",
  "Baby Yellow",
  "Gold",
  "Butter",
  "Golden Poppy",
  "Sunflower",
  "Buzz",
  "Vibrant Yellow",
  "Cadmium Lemon",
  "Mustard",
  "Relax Yellow",
  "Snapchat Yellow",
  "Royal Yellow",
  "Butter",
  "Fire Yellow",
  "Cream",
  "Rainbow Yellow",
  "Golden Rod",
  "Cadmium",
  "Cyber",
  "Saffron",
  "Saffron",
  "Ochre Yellow",
  "Canary Yellow",
  "Candy Corn",
  "Gargoyle Gas",
  "Pastel Yellow",
  "Aureolin",
  "Hot Yellow",
  "Custard",
  "Sand Yellow",
  "Daffodil",
  "Golden Poppy",
  "Golden Sand",
  "Munsell Yellow",
  "Golden Yellow",
  "Corn",
  "Mikado",
  "Gorse",
  "Hansa Yellow",
  "Hathaway",
  "Holiday",
  "Icterine",
  "Jasmine",
  "Manz",
  "Citrine",
  "Banana Mania",
  "Dijon",
  "Marigold Yellow",
  "Selective Yellow",
  "Empire",
  "Lemon Chiffon",
  "Vintage Yellow",
  "Neon Yellow",
  "Green",
  "Forest",
  "Emerald",
  "Pine",
  "Jungle",
  "Hunter",
  "Mint",
  "Green (Munsell)",
  "Olive",
  "Jade",
  "Pine",
  "Bluish Green",
  "Phthalo Green",
  "Jewel",
  "Algae",
  "Malachite",
  "Pistachio",
  "Mantis",
  "Algae",
  "Christmas Green",
  "Amazon",
  "Lime",
  "Android",
  "Lucky Break",
  "Ao",
  "Jungle Juice",
  "Chartreuse",
  "Anise",
  "Office Green",
  "Artichoke – Pantone",
  "Apple",
  "Ocean Green",
  "Army Green",
  "Parsley",
  "Artichoke",
  "Irish",
  "Neon Green",
  "Asparagus",
  "Polished Pine",
  "Robin Hood",
  "Sea Green",
  "John Deere Green",
  "Viridian",
  "Atlantis",
  "Sacramento",
  "Hunter",
  "Hunter",
  "Avocado",
  "Shamrock",
  "Baby Green",
  "Bay Leaf",
  "Sage",
  "San Felix",
  "Bilbao",
  "Bitter Lemon",
  "Bluish Green",
  "Booger",
  "Bottle Green",
  "Breaker Bay",
  "Bright Green",
  "Verdun",
  "Brilliant Emerald",
  "British Racing",
  "Brunswick",
  "Kelly Green",
  "French Lime",
  "Cactus",
  "Cadmium",
  "Cal Poly",
  "Camarone",
  "Cardin",
  "Castleton",
  "Pear",
  "Pear",
  "Chlorophyll",
  "Celadon",
  "Chateau",
  "Cinnabar",
  "Cobalt Green",
  "Corn Green",
  "Paolo Veronese",
  "Citrus",
  "Como",
  "Cool Green",
  "Turquoise Green",
  "Crusoe",
  "Dark Emerald",
  "Dark Fern",
  "Dark Forest Green",
  "Dark Green",
  "Dark Mint",
  "Spring",
  "Dark Spring",
  "Dartmouth",
  "Deep Spring",
  "Dollar Bill",
  "Dusty Green",
  "Foam Green",
  "Freedom",
  "Old Moss Green",
  "Fringy Flower",
  "Fruit Salad",
  "Go Green",
  "Gossamer",
  "Gossip",
  "Green Gray",
  "Green Haze",
  "Green Pea",
  "Caribbean",
  "Greenish",
  "Jeepers Creepers",
  "Observatory",
  "Keppel",
  "Gum Leaf",
  "Illuminating Emerald",
  "Dark Aquamarine",
  "Seafoam",
  "Genoa",
  "Teal",
  "Caesar",
  "Deep Sea",
  "Dull Teal",
  "Dusty Teal",
  "Niagara",
  "Blue",
  "Navy",
  "Traditional Royal Blue",
  "Egyptian",
  "Cerulean",
  "Royal",
  "Baby Blue",
  "Tiffany",
  "Carolina",
  "Cobalt Blue",
  "New Midnight",
  "Turquoise",
  "Aegean",
  "Denim",
  "Munsell",
  "Pacific",
  "Pacific",
  "Nice Blue",
  "San Marino",
  "Lapis",
  "Mavericks",
  "Sapphire",
  "Science Blue",
  "Sea Blue",
  "Dodger",
  "Admiral Blue",
  "French Blue",
  "Spanish Blue",
  "B’dazzled",
  "Ice Blue",
  "Turquoise Blue",
  "Fluorescent",
  "Bright Turquoise",
  "Light Turquoise",
  "Blue Light",
  "Seafoam Blue",
  "Sky Blue",
  "Ocean Blue",
  "Alaskan",
  "Sky Blue Light",
  "Slate",
  "Snap",
  "Star Command",
  "Steel Blue Light",
  "Teal Blue",
  "Azure",
  "Jordy",
  "Bleu De France",
  "Imperial",
  "Ultramarine",
  "Brewers",
  "Peacock",
  "Absolute Zero",
  "Fresh Air",
  "Celadon",
  "Stone",
  "Spruce",
  "Byzantine",
  "Cornflower",
  "Crayola Blue",
  "Celeste",
  "Greenish Blue",
  "Frozen",
  "Aero",
  "Marine",
  "Capri",
  "Catalina",
  "Fountain",
  "Galactica",
  "Air Force",
  "Blue Ribbon",
  "Blue Gray",
  "Allports",
  "Anakiwa",
  "Blueberry",
  "Danube",
  "Bright Blue",
  "Indigo Blue",
  "Trypan",
  "Picotee",
  "Chelsea",
  "Blue Jeans",
  "Aquamarine Blue",
  "Aquarius",
  "Bluish",
  "Cerulean Frost",
  "Charlotte",
  "Peacock",
  "Chathams",
  "Dusk Blue",
  "Malibu",
  "Clear Blue",
  "Cool Blue",
  "Aqua",
  "Robin Egg",
  "Bright Cerulean",
  "Arapawa",
  "Ball",
  "Believe",
  "Phthalo Blue",
  "Oxford",
  "Biscay",
  "Bright Navy",
  "Bright Sky",
  "Comfort Zone",
  "Arctic",
  "Lure",
  "Polynesian",
  "Congress Blue",
  "Cyan Azure",
  "Cyan Blue",
  "Cyan Blue Azure",
  "Bayern",
  "Pantone Blue",
  "Dark Blue",
  "Dark Midnight",
  "Dark Pastel Blue",
  "Deep Sky",
  "Slate",
  "Savoy",
  "Duke",
  "Dull Blue",
  "Light Cerulean",
  "Limitless",
  "Ford",
  "IBM",
  "Twitter",
  "Dell",
  "Little Boy",
  "Imperial Purple",
  "Plum",
  "Mauve",
  "Tyrian",
  "Mulberry",
  "Periwinkle",
  "Orchid",
  "Purple Heart",
  "Affair",
  "Byzantine",
  "Purpureus",
  "Boogie Wonderland",
  "Bright Lavender",
  "Bruise",
  "Palatinate",
  "French Mauve",
  "Lavender Blush",
  "Thistle",
  "Mountbatten",
  "Ooh La",
  "English Violet",
  "Abracadabra",
  "Fuchsia",
  "Jam",
  "Amaranth Purple",
  "Phlox",
  "Iris",
  "Cardinal",
  "Carnival",
  "Ce Soir",
  "Pale Purple",
  "French Lilac",
  "Eggplant",
  "Indigo",
  "Veronica",
  "Centre Stage",
  "Long Distance",
  "Centaurian",
  "Bubblegum",
  "Chapta And Verse",
  "Lipstick Stain",
  "Bright Lilac",
  "Bright Purple",
  "Amethyst",
  "Fog",
  "Barney",
  "Dull Purple",
  "Smyrna",
  "Dusky Purple",
  "Dusty Lavender",
  "Little Princess",
  "Faded Purple",
  "East Side",
  "Clairvoyant",
  "Autumn Purple",
  "Baby Purple",
  "Purplish Orchid",
  "African Violet",
  "Cold Purple",
  "Dreamweaver",
  "Black Currant",
  "Dark Lavender",
  "Dark Lilac",
  "Fun Fair",
  "Deep Mauve",
  "Pastel Purple",
  "Biloba Flower",
  "Blurple",
  "Berry – Crayola",
  "Glossy Grape",
  "Heather",
  "Plum Web",
  "Hot Purple",
  "Royal Purple",
  "Funtasia",
  "Traditional Purple",
  "Genie",
  "Purplish",
  "Old Lavender",
  "Languid Lavender",
  "Wisteria",
  "Lavender",
  "Magnolia",
  "Lavender Blue",
  "Lavender Gray",
  "Razzmic Berry",
  "Mauveine",
  "Lightish Purple",
  "Lilac",
  "Carolina Plum",
  "Lilac Bush",
  "Lily",
  "London Hue",
  "Long Shot",
  "Kalamata",
  "Lilac Luster",
  "Lavender",
  "Lavender Purple",
  "Lenurple",
  "Light Blue Violet",
  "Violet",
  "Rhythm",
  "Pale Lavender",
  "Pastel Violet",
  "Pomp And Power",
  "Regalia",
  "Brown",
  "Burnt Umber",
  "Russet",
  "Auburn",
  "Bronze",
  "Tan",
  "Brown Ochre",
  "Copper",
  "Copper",
  "Cigar",
  "Chocolate",
  "Cinnamon",
  "Burnt Maroon",
  "Ochre",
  "Taupe",
  "Cocoa",
  "Light Brown",
  "Cajun",
  "Magma",
  "Hawaiian Tan",
  "Bean",
  "Saddle",
  "Hazard",
  "Heartwood",
  "Chocolate Brown",
  "Sienna",
  "Cape Palliser",
  "Antique Brass",
  "Grizzly",
  "Brownie",
  "Hairy Heath",
  "Mai Tai",
  "Burnt Sienna",
  "Ginger",
  "Cedar",
  "Sepia",
  "Scoria",
  "Tan",
  "Fawn",
  "Heatwave",
  "Clay",
  "Rust",
  "Meteor",
  "Charisma",
  "Buff",
  "Lone Ranger",
  "Buffalo",
  "Bull Shot",
  "Bullion",
  "Mexican Wave",
  "Claypot",
  "Bole",
  "Bungy",
  "Coffee",
  "Burnished Orange",
  "Hot Chocolate",
  "Mustang",
  "Chelsea Gem",
  "Cinnamon",
  "Buttered Rum",
  "Brown Rust",
  "Brown Sugar",
  "Brownie Points",
  "Piper",
  "Kakaramea",
  "Hukanui",
  "Brownish",
  "Rust Brown",
  "Brownish Gray",
  "Auburn",
  "Ash Brown",
  "Adobe",
  "Jalapeno",
  "Golden Brown",
  "Acorn",
  "Afficionado",
  "Alter Ego",
  "Jarrah Stain",
  "Axis",
  "Brown Nose",
  "Footloose",
  "Jazz",
  "Mahogany",
  "French Puce",
  "Kenyan Copper",
  "Goldie",
  "Baker’S Chocolate",
  "Gold Dust",
  "Dynamite",
  "Blast Yellow",
  "Boomerang",
  "Coconut",
  "Kobicha",
  "Barley Corn",
  "Caramel",
  "Bracken",
  "Brazil",
  "Caput Mortuum",
  "Tuscan Brown",
  "Ecru",
  "Deep Brown",
  "Bitter Chocolate",
  "Hawaiian Brown",
  "Brick",
  "Brandy",
  "Chamoisee",
  "Carnaby Tan",
  "Peru",
  "Double Lumberjack",
  "Double Otter",
  "Beige",
  "Khaki",
  "Almond",
  "Buttercream",
  "Butter Toast",
  "Desert Gray",
  "Beige Linen",
  "Mojave Desert",
  "Latte",
  "Feather Brown",
  "Fortune Cookie",
  "Beaver",
  "Wheat",
  "Dark Vanilla",
  "French Beige",
  "Burlywood",
  "Cashmere",
  "Croissant",
  "Café Au Lait",
  "Wood brown",
  "Sand",
  "Champagne",
  "Froth Green",
  "Gallery",
  "Gargoyle",
  "Goldmine",
  "Half Oilskin",
  "Hampton",
  "Haystack",
  "Honey",
  "Howlin Wolf",
  "Incognito",
  "Indian Khaki",
  "Janna",
  "Joss",
  "Kangaroo",
  "Light French Beige",
  "Fossil",
  "Manilla",
  "Matchstick",
  "Sanctuary",
  "Sandspit Brown",
  "Bone",
  "Acadia",
  "All Black",
  "Almost Black",
  "Asphalt",
  "Aztec",
  "Baltic Sea",
  "Banjul",
  "Black",
  "Blackout",
  "Black Bean",
  "Black Leather Jacket",
  "Onyx",
  "Black Rock",
  "Black Russian",
  "Blue Bark",
  "Blue Charcoal",
  "Bunker",
  "Caffeine",
  "Cannon Black",
  "Chimney Sweep",
  "Cinder",
  "Cod Gray",
  "Cyanish Black",
  "Double Barbecue",
  "Double Cod Gray",
  "Ebony",
  "Eerie Black",
  "Foundry",
  "Gordons Green",
  "Green Waterloo",
  "Greenish Black",
  "Gray",
  "Gunmetal",
  "Ivory Black",
  "Jacko Bean",
  "Jaguar",
  "Magentaish Black",
  "Maire",
  "Marshland",
  "Maxwell Smart",
  "Smoky Black",
  "Gray",
  "Ajay",
  "Abbey",
  "Silver",
  "Charcoal",
  "Thunder",
  "Antique White",
  "Snow",
  "Gray Owl",
  "Carbon Gray",
  "Gainsboro",
  "Aquashield Half Tapa",
  "Gray Dolphin",
  "Ash Gray",
  "Gray Goose",
  "Avatar",
  "Basalt",
  "Bombay",
  "Tapa",
  "Tasman",
  "Boulder",
  "Boulder",
  "Cadet Gray",
  "Casper",
  "Cathedral",
  "Charcoal Gray",
  "Chicago",
  "Chicane",
  "Cobblestone",
  "Condor",
  "Dark Greenish Gray",
  "Dark Medium Gray",
  "Dark Gray",
  "Dark Olivish Gray",
  "Davy’S Gray",
  "Davy Gray",
  "Delta",
  "Delta Gray",
  "Detroit",
  "Dim Gray",
  "Dark Silver",
  "Dna",
  "Double Concrete",
  "Dusty Gray",
  "Double Friar Gray",
  "Graphite Gray",
  "Double Rakaia",
  "Double Schooner",
  "Rustic Gray",
  "Double Surrender",
  "Double Trojan",
  "Dove Gray",
  "Dusted Blue",
  "Foggy Gray",
  "Silk Gray",
  "White Gray",
  "Agreeable Gray",
  "Forcefield",
  "Gentle Gray",
  "Forecast",
  "Battleship Gray",
  "Freestyling",
  "French Gray",
  "Friar Gray",
  "Gannet Gray",
  "Gauntlet",
  "Geyser",
  "Sea Gray",
  "Ghost",
  "Gray Chateau",
  "Gray Nurse",
  "Chrome",
  "Gray Suit",
  "Dull Gray",
  "Gunsmoke",
  "Half Tapa",
  "Iron",
  "Half Tasman",
  "Half Taupe Gray",
  "Half Truffle",
  "Smokey Gray",
  "Identity",
  "Storm Gray",
  "Imagine",
  "Ironside Gray",
  "Nevada",
  "Seal",
  "Ivory",
  "Kensington Gray",
  "Abalone",
  "Light Gray",
  "Medium Gray",
  "Loblolly",
  "Mercury",
  "Timberwolf",
  "Nickel",
  "Manatee",
  "Meridian",
  "Outer Space",
  "Metro",
  "Midwinter Mist",
  "Oslo Gray",
  "Pastel Gray",
  "Pink Gray",
  "Quick Silver",
  "Roman Silver",
  "Barely There",
  "Rugged Lavender",
  "Scorpion",
  "Seashell",
  "Alabaster",
  "Old Wood",
  "Azure Mist",
  "Oyster White",
  "Vista",
  "Rice",
  "Baby Powder",
  "Floral",
  "Bianca",
  "Daisy",
  "Bluish White",
  "Milk",
  "Natural White",
  "Powder",
  "Old Lace",
  "White Dove",
  "Pearl",
  "Catskill",
  "Spring",
  "Citrine White",
  "Cyanish White",
  "Coconut Butter",
  "Designer White",
  "White Whisper",
  "Double Alabaster",
  "Double Barely There",
  "Eighth Ash",
  "Bright White",
  "Ghost",
  "Glistening",
  "Eggshell",
  "Greenish White",
  "Half Orchid White",
  "Dutch White",
  "Half Rice Cake",
  "Half Sea Fog",
  "Half White Pointer",
  "Isabelline",
  "Merino",
  "Manyana",
  "Marble",
  "Porcelain",
  "Promenade",
  "Greek Villa",
  "Saltpan",
  "Simply White",
  "Cough Mixture",
  "Snow Drift",
  "Soapstone",

]

module.exports = colors